[build]
  # Build command for Next.js with Netlify
  command = "npm run build"
  
  # Output directory for Next.js build
  publish = ".next"
  
  # Base directory (since we're deploying from frontend folder)
  base = "frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"

# Use Netlify's Next.js plugin for automatic configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
